<?php
require 'config.php';

if (!isset($_SESSION['userData'])) {
    header('location:login.php');
}

require_once 'googleLib/GoogleAuthenticator.php';
$ga 		= new GoogleAuthenticator();
$secret= 'DASJDGSAJDGSA'; //googlelib -random üretebiliriz
$qrCodeUrl 	= $ga->getQRCodeGoogleUrl(implode(" ", $_SESSION['userData']), $secret,'www.bynogame.com');


?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Google Two Factor Authentication Login with PHP</title>


</head>
<body class="a2z-wrapper">


<section class="a2z-area">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="form-area register-from">
                    <div class="form-content">
                        <h2>Google Two Factor Authentication</h2>
                        <p>Enter the verification code generated by Google Authenticator app on your phone.</p>

                    </div>


                    <div class="form-input">
                        <h2>Enter Code</h2>
                        <form name="reg" action="auth.php" method="POST">

                            <div class="form-group">
                                <img src='<?php echo $qrCodeUrl; ?>'/>
                            </div>

                            <div class="form-group">
                                <input type="text" name="code" id="code" autocomplete="off" value="" required>
                                <label>Enter Google Authenticator Code</label>
                            </div>

                            <div class="a2z-button">
                                <button type="submit" class="a2z-btn">Submit</button>
                            </div>
                            <br>
                            <a class="logout-btn" href="logout.php">Logout</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>